name: Deploy Zensical site to GitHub Pages

on:
  push:
    branches:
      - main

# Erlaubt dem Job, ein GitHub Pages Deployment durchzuführen
permissions:
  pages: write
  id-token: write

# Verhindert, dass mehrere Deployments gleichzeitig laufen
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Caching Zensical
      - name: Configure Cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: zensical-${{ env.cache_id }}
          path: ~/.cache 
          restore-keys: |
            zensical-

      # Installation Zensical und Plugins
      - name: Install dependencies
        run: |
          pip install zensical

      - name: Build Zensical site
        run: |
          zensical build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      # Direktes Deployment ohne gh-pages Branch
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4